dist: bionic

language: minimal

env:
  global:
    - REPO=docksal/varnish

  matrix:
    - VERSION=6.0
    - VERSION=6.2

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - make
  - make start
  - make test

after_success:
  - make release

after_failure:
  - make logs
