dist: xenial

language: minimal

env:
  global:
    - REPO=docksal/varnish

  matrix:
    - VERSION=6.1 TAGS=6.1,6,latest
    - VERSION=5.2 TAGS=5.2,5
    - VERSION=4.1 TAGS=4.1,4

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - cd ${VERSION}
  - make
  - make test

after_success:
  - ${TRAVIS_BUILD_DIR}/release.sh

after_failure:
  - make logs
